"""First migrate

Revision ID: 100f44ca7a16
Revises: 
Create Date: 2020-05-12 15:53:05.988634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100f44ca7a16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
