"""add user chat id Column

Revision ID: 6a2a26fcdb3c
Revises: 100f44ca7a16
Create Date: 2020-05-14 15:30:07.927267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2a26fcdb3c'
down_revision = '100f44ca7a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'chat_id')
    # ### end Alembic commands ###
