"""+subscribe

Revision ID: e0accfc3c577
Revises: eb4575086af9
Create Date: 2020-06-04 15:42:03.249738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0accfc3c577'
down_revision = 'eb4575086af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('subscribe', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'subscribe')
    # ### end Alembic commands ###
