"""New class Ask_for_help

Revision ID: eb4575086af9
Revises: 6a2a26fcdb3c
Create Date: 2020-05-15 14:12:28.328266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4575086af9'
down_revision = '6a2a26fcdb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ask_for_help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('ask_for_help', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ask_for_help')
    # ### end Alembic commands ###
